version: "3.8"

services:
  mongodb:
    image: mongo:7.0.11
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db:
